// data.jsx — フォーメーション定義と選手データ
// 座標系: x,y は 0–100。y=92 がGK側（下）、y=18 が前線（上）

const FORMATIONS = [
  {
    id: '3-4-2-1',
    label: '3-4-2-1',
    tagline: '森保J の十八番',
    slots: [
      { id: 'gk',   role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lcb',  role: 'DF', label: 'CB',  x: 25, y: 76 },
      { id: 'ccb',  role: 'DF', label: 'CB',  x: 50, y: 80 },
      { id: 'rcb',  role: 'DF', label: 'CB',  x: 75, y: 76 },
      { id: 'lwb',  role: 'MF', label: 'LWB', x: 8,  y: 56 },
      { id: 'lcm',  role: 'MF', label: 'CM',  x: 36, y: 58 },
      { id: 'rcm',  role: 'MF', label: 'CM',  x: 64, y: 58 },
      { id: 'rwb',  role: 'MF', label: 'RWB', x: 92, y: 56 },
      { id: 'lsh',  role: 'MF', label: 'SH',  x: 32, y: 34 },
      { id: 'rsh',  role: 'MF', label: 'SH',  x: 68, y: 34 },
      { id: 'st',   role: 'FW', label: 'ST',  x: 50, y: 16 },
    ],
  },
  {
    id: '3-1-4-2',
    label: '3-1-4-2',
    tagline: '超攻撃的布陣',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK', x: 50, y: 92 },
      { id: 'lcb', role: 'DF', label: 'CB', x: 25, y: 76 },
      { id: 'ccb', role: 'DF', label: 'CB', x: 50, y: 80 },
      { id: 'rcb', role: 'DF', label: 'CB', x: 75, y: 76 },
      { id: 'dm',  role: 'MF', label: 'DM', x: 50, y: 60 },
      { id: 'lm',  role: 'MF', label: 'LM', x: 10, y: 44 },
      { id: 'lcm', role: 'MF', label: 'CM', x: 36, y: 42 },
      { id: 'rcm', role: 'MF', label: 'CM', x: 64, y: 42 },
      { id: 'rm',  role: 'MF', label: 'RM', x: 90, y: 44 },
      { id: 'lst', role: 'FW', label: 'ST', x: 38, y: 20 },
      { id: 'rst', role: 'FW', label: 'ST', x: 62, y: 20 },
    ],
  },
  {
    id: '3-4-3',
    label: '3-4-3',
    tagline: '攻撃的3バック',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lcb', role: 'DF', label: 'CB',  x: 25, y: 76 },
      { id: 'ccb', role: 'DF', label: 'CB',  x: 50, y: 80 },
      { id: 'rcb', role: 'DF', label: 'CB',  x: 75, y: 76 },
      { id: 'lwb', role: 'MF', label: 'LWB', x: 8,  y: 54 },
      { id: 'lcm', role: 'MF', label: 'CM',  x: 36, y: 56 },
      { id: 'rcm', role: 'MF', label: 'CM',  x: 64, y: 56 },
      { id: 'rwb', role: 'MF', label: 'RWB', x: 92, y: 54 },
      { id: 'lw',  role: 'FW', label: 'LW',  x: 20, y: 24 },
      { id: 'st',  role: 'FW', label: 'ST',  x: 50, y: 18 },
      { id: 'rw',  role: 'FW', label: 'RW',  x: 80, y: 24 },
    ],
  },
  {
    id: '4-4-2',
    label: '4-4-2',
    tagline: '王道フラット',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK', x: 50, y: 92 },
      { id: 'lb',  role: 'DF', label: 'LB', x: 12, y: 75 },
      { id: 'lcb', role: 'DF', label: 'CB', x: 36, y: 78 },
      { id: 'rcb', role: 'DF', label: 'CB', x: 64, y: 78 },
      { id: 'rb',  role: 'DF', label: 'RB', x: 88, y: 75 },
      { id: 'lm',  role: 'MF', label: 'LM', x: 12, y: 50 },
      { id: 'lcm', role: 'MF', label: 'CM', x: 36, y: 52 },
      { id: 'rcm', role: 'MF', label: 'CM', x: 64, y: 52 },
      { id: 'rm',  role: 'MF', label: 'RM', x: 88, y: 50 },
      { id: 'lst', role: 'FW', label: 'ST', x: 36, y: 22 },
      { id: 'rst', role: 'FW', label: 'ST', x: 64, y: 22 },
    ],
  },
  {
    id: '4-2-3-1',
    label: '4-2-3-1',
    tagline: 'バランス型・主流',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lb',  role: 'DF', label: 'LB',  x: 12, y: 75 },
      { id: 'lcb', role: 'DF', label: 'CB',  x: 35, y: 78 },
      { id: 'rcb', role: 'DF', label: 'CB',  x: 65, y: 78 },
      { id: 'rb',  role: 'DF', label: 'RB',  x: 88, y: 75 },
      { id: 'ldm', role: 'MF', label: 'DM',  x: 36, y: 58 },
      { id: 'rdm', role: 'MF', label: 'DM',  x: 64, y: 58 },
      { id: 'lw',  role: 'MF', label: 'LW',  x: 14, y: 38 },
      { id: 'am',  role: 'MF', label: 'AM',  x: 50, y: 38 },
      { id: 'rw',  role: 'MF', label: 'RW',  x: 86, y: 38 },
      { id: 'st',  role: 'FW', label: 'ST',  x: 50, y: 18 },
    ],
  },
  {
    id: '4-1-4-1',
    label: '4-1-4-1',
    tagline: '守備バランス',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK', x: 50, y: 92 },
      { id: 'lb',  role: 'DF', label: 'LB', x: 12, y: 75 },
      { id: 'lcb', role: 'DF', label: 'CB', x: 36, y: 78 },
      { id: 'rcb', role: 'DF', label: 'CB', x: 64, y: 78 },
      { id: 'rb',  role: 'DF', label: 'RB', x: 88, y: 75 },
      { id: 'dm',  role: 'MF', label: 'DM', x: 50, y: 60 },
      { id: 'lm',  role: 'MF', label: 'LM', x: 12, y: 40 },
      { id: 'lcm', role: 'MF', label: 'CM', x: 36, y: 42 },
      { id: 'rcm', role: 'MF', label: 'CM', x: 64, y: 42 },
      { id: 'rm',  role: 'MF', label: 'RM', x: 88, y: 40 },
      { id: 'st',  role: 'FW', label: 'ST', x: 50, y: 18 },
    ],
  },
  {
    id: '4-3-1-2',
    label: '4-3-1-2',
    tagline: 'クラシックダイヤ',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK', x: 50, y: 92 },
      { id: 'lb',  role: 'DF', label: 'LB', x: 12, y: 75 },
      { id: 'lcb', role: 'DF', label: 'CB', x: 36, y: 78 },
      { id: 'rcb', role: 'DF', label: 'CB', x: 64, y: 78 },
      { id: 'rb',  role: 'DF', label: 'RB', x: 88, y: 75 },
      { id: 'lcm', role: 'MF', label: 'CM', x: 22, y: 56 },
      { id: 'dm',  role: 'MF', label: 'DM', x: 50, y: 60 },
      { id: 'rcm', role: 'MF', label: 'CM', x: 78, y: 56 },
      { id: 'am',  role: 'MF', label: 'AM', x: 50, y: 36 },
      { id: 'lst', role: 'FW', label: 'ST', x: 36, y: 18 },
      { id: 'rst', role: 'FW', label: 'ST', x: 64, y: 18 },
    ],
  },
  {
    id: '3-5-2',
    label: '3-5-2',
    tagline: '中盤厚め',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lcb', role: 'DF', label: 'CB',  x: 25, y: 76 },
      { id: 'ccb', role: 'DF', label: 'CB',  x: 50, y: 80 },
      { id: 'rcb', role: 'DF', label: 'CB',  x: 75, y: 76 },
      { id: 'lwb', role: 'MF', label: 'LWB', x: 8,  y: 54 },
      { id: 'lcm', role: 'MF', label: 'CM',  x: 30, y: 52 },
      { id: 'ccm', role: 'MF', label: 'CM',  x: 50, y: 48 },
      { id: 'rcm', role: 'MF', label: 'CM',  x: 70, y: 52 },
      { id: 'rwb', role: 'MF', label: 'RWB', x: 92, y: 54 },
      { id: 'lst', role: 'FW', label: 'ST',  x: 38, y: 22 },
      { id: 'rst', role: 'FW', label: 'ST',  x: 62, y: 22 },
    ],
  },
  {
    id: '5-3-2',
    label: '5-3-2',
    tagline: '堅守速攻',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lwb', role: 'DF', label: 'LWB', x: 8,  y: 70 },
      { id: 'lcb', role: 'DF', label: 'CB',  x: 28, y: 78 },
      { id: 'ccb', role: 'DF', label: 'CB',  x: 50, y: 80 },
      { id: 'rcb', role: 'DF', label: 'CB',  x: 72, y: 78 },
      { id: 'rwb', role: 'DF', label: 'RWB', x: 92, y: 70 },
      { id: 'lcm', role: 'MF', label: 'CM',  x: 26, y: 50 },
      { id: 'ccm', role: 'MF', label: 'CM',  x: 50, y: 50 },
      { id: 'rcm', role: 'MF', label: 'CM',  x: 74, y: 50 },
      { id: 'lst', role: 'FW', label: 'ST',  x: 38, y: 22 },
      { id: 'rst', role: 'FW', label: 'ST',  x: 62, y: 22 },
    ],
  },
  {
    id: '5-4-1',
    label: '5-4-1',
    tagline: '超守備的',
    slots: [
      { id: 'gk',  role: 'GK', label: 'GK',  x: 50, y: 92 },
      { id: 'lwb', role: 'DF', label: 'LWB', x: 8,  y: 70 },
      { id: 'lcb', role: 'DF', label: 'CB',  x: 28, y: 78 },
      { id: 'ccb', role: 'DF', label: 'CB',  x: 50, y: 80 },
      { id: 'rcb', role: 'DF', label: 'CB',  x: 72, y: 78 },
      { id: 'rwb', role: 'DF', label: 'RWB', x: 92, y: 70 },
      { id: 'lm',  role: 'MF', label: 'LM',  x: 14, y: 50 },
      { id: 'lcm', role: 'MF', label: 'CM',  x: 36, y: 52 },
      { id: 'rcm', role: 'MF', label: 'CM',  x: 64, y: 52 },
      { id: 'rm',  role: 'MF', label: 'RM',  x: 86, y: 50 },
      { id: 'st',  role: 'FW', label: 'ST',  x: 50, y: 20 },
    ],
  },
  {
    id: 'other',
    label: 'その他',
    tagline: '自由配置 (4-3-3スタート)',
    slots: [
      { id: 'gk', role: 'GK', label: 'GK', x: 50, y: 92 },
      { id: 's1', role: 'DF', label: 'DF', x: 12, y: 75 },
      { id: 's2', role: 'DF', label: 'DF', x: 36, y: 78 },
      { id: 's3', role: 'DF', label: 'DF', x: 64, y: 78 },
      { id: 's4', role: 'DF', label: 'DF', x: 88, y: 75 },
      { id: 's5', role: 'MF', label: 'MF', x: 24, y: 52 },
      { id: 's6', role: 'MF', label: 'MF', x: 50, y: 54 },
      { id: 's7', role: 'MF', label: 'MF', x: 76, y: 52 },
      { id: 's8', role: 'FW', label: 'FW', x: 20, y: 24 },
      { id: 's9', role: 'FW', label: 'FW', x: 50, y: 18 },
      { id: 's10',role: 'FW', label: 'FW', x: 80, y: 24 },
    ],
  },
];

// 26名: 2026年北中米W杯 日本代表（添付画像より）
const PLAYERS = [
  // GK
  { id: 'p01', num: 1,  pos: 'GK', name: '鈴木 彩艶',   nameRoman: 'Suzuki Z.',  club: 'パルマ・カルチョ' },
  { id: 'p12', num: 12, pos: 'GK', name: '大迫 敬介',   nameRoman: 'Osako K.',   club: 'サンフレッチェ広島' },
  { id: 'p23', num: 23, pos: 'GK', name: '早川 友基',   nameRoman: 'Hayakawa Y.', club: '鹿島アントラーズ' },
  // DF
  { id: 'p02', num: 2,  pos: 'DF', name: '菅原 由勢',   nameRoman: 'Sugawara Y.', club: 'ヴェルダー・ブレーメン' },
  { id: 'p03', num: 3,  pos: 'DF', name: '伊藤 洋輝',   nameRoman: 'Ito H.',      club: 'バイエルン・ミュンヘン' },
  { id: 'p04', num: 4,  pos: 'DF', name: '板倉 滉',     nameRoman: 'Itakura K.',  club: 'アヤックス' },
  { id: 'p05', num: 5,  pos: 'DF', name: '谷口 彰悟',   nameRoman: 'Taniguchi S.',club: 'シントトロイデンVV' },
  { id: 'p16', num: 16, pos: 'DF', name: '冨安 健洋',   nameRoman: 'Tomiyasu T.', club: 'アヤックス' },
  { id: 'p19', num: 19, pos: 'DF', name: '瀬古 歩夢',   nameRoman: 'Seko A.',     club: 'ル・アーヴルAC' },
  { id: 'p20', num: 20, pos: 'DF', name: '渡辺 剛',     nameRoman: 'Watanabe T.', club: 'フェイエノールト' },
  { id: 'p22', num: 22, pos: 'DF', name: '長友 佑都',   nameRoman: 'Nagatomo Y.', club: 'FC東京' },
  { id: 'p26', num: 26, pos: 'DF', name: '鈴木 淳之介', nameRoman: 'Suzuki J.',   club: 'FCコペンハーゲン' },
  // MF
  { id: 'p06', num: 6,  pos: 'MF', name: '遠藤 航',     nameRoman: 'Endo W.',    club: 'リバプールFC', captain: true },
  { id: 'p07', num: 7,  pos: 'MF', name: '久保 建英',   nameRoman: 'Kubo T.',    club: 'レアル・ソシエダード' },
  { id: 'p08', num: 8,  pos: 'MF', name: '鎌田 大地',   nameRoman: 'Kamada D.',  club: 'クリスタル・パレス' },
  { id: 'p10', num: 10, pos: 'MF', name: '堂安 律',     nameRoman: 'Doan R.',    club: 'アイントラハト・フランクフルト' },
  { id: 'p13', num: 13, pos: 'MF', name: '田中 碧',     nameRoman: 'Tanaka A.',  club: 'リーズ・ユナイテッド' },
  { id: 'p14', num: 14, pos: 'MF', name: '伊東 純也',   nameRoman: 'Ito J.',     club: 'KRCゲンク' },
  { id: 'p15', num: 15, pos: 'MF', name: '中村 敬斗',   nameRoman: 'Nakamura K.',club: 'スタッド・ランス' },
  { id: 'p17', num: 17, pos: 'MF', name: '佐野 海舟',   nameRoman: 'Sano K.',    club: 'マインツ05' },
  { id: 'p21', num: 21, pos: 'MF', name: '鈴木 唯人',   nameRoman: 'Suzuki Y.',  club: 'SCフライブルク' },
  // FW
  { id: 'p09', num: 9,  pos: 'FW', name: '上田 綺世',   nameRoman: 'Ueda A.',    club: 'フェイエノールト' },
  { id: 'p11', num: 11, pos: 'FW', name: '前田 大然',   nameRoman: 'Maeda D.',   club: 'セルティック' },
  { id: 'p18', num: 18, pos: 'FW', name: '小川 航基',   nameRoman: 'Ogawa K.',   club: 'NECナイメヘン' },
  { id: 'p24', num: 24, pos: 'FW', name: '塩貝 健人',   nameRoman: 'Shiogai K.', club: 'VfLヴォルフスブルク' },
  { id: 'p25', num: 25, pos: 'FW', name: '後藤 啓介',   nameRoman: 'Goto K.',    club: 'シントトロイデンVV' },
];

Object.assign(window, { FORMATIONS, PLAYERS });
